"""Utility constants and helpers shared across training and inference."""

from __future__ import annotations

import dataclasses
import hashlib
from dataclasses import dataclass, field
from typing import TYPE_CHECKING

from PIL import Image, ImageDraw, ImageFont

if TYPE_CHECKING:
    pass

# fmt: off
CLASS_NAMES: list[str] = [
    # January (Pine)
    "01-hkr-tsuru", "01-kas", "01-tan-akatan",
    # February (Plum)
    "02-kas", "02-tan-akatan", "02-tne-uguisu",
    # March (Cherry)
    "03-hkr-maku", "03-kas", "03-tan-akatan",
    # April (Wisteria)
    "04-kas", "04-tan-muji", "04-tne-hototogisu",
    # May (Iris)
    "05-kas", "05-tan-muji", "05-tne-yatsuhashi",
    # June (Peony)
    "06-kas", "06-tan-aotan", "06-tne-cho",
    # July (Bush Clover)
    "07-kas", "07-tan-muji", "07-tne-inoshishi",
    # August (Susuki Grass)
    "08-hkr-tsuki", "08-kas", "08-tne-kari",
    # September (Chrysanthemum)
    "09-kas", "09-tan-aotan", "09-tne-sakazuki",
    # October (Maple)
    "10-kas", "10-tan-aotan", "10-tne-shika",
    # November (Rain)
    "11-hkr-michikaze", "11-kas", "11-tan-muji", "11-tne-tsubame",
    # December (Paulownia)
    "12-hkr-hooh", "12-kas",
]
# fmt: on


@dataclass
class TrainConfig:
    """All hyperparameters and paths for a training run.

    Pass this to ``train()`` in train.py, and to ``setup_wandb()`` here.
    Using a dataclass (rather than a dict) gives IDE auto-complete and a
    clean ``__repr__`` for free.
    """

    model: str = "yolo11n.pt"
    data_dir: str = "data/raw"
    data_yaml: str = ""           # auto-generated by prepare_dataset() in train.py
    epochs: int = 100
    imgsz: int = 640
    batch: int = 16
    device: str = "0"
    project: str = "runs/train"
    name: str = "hanafuda_yolo11n"
    workers: int = 4
    patience: int = 20
    val_split: float = 0.2        # fraction of data used for validation
    seed: int = 42                # random seed for reproducible train/val split
    wandb_project: str = "hanafuda-yolo"
    wandb_entity: str = field(default="")  # override via env var WANDB_ENTITY

    def as_yolo_kwargs(self) -> dict:
        """Return only the kwargs that ultralytics YOLO.train() accepts."""
        exclude = {"data_dir", "data_yaml", "val_split", "seed", "wandb_project", "wandb_entity"}
        raw = dataclasses.asdict(self)
        raw["data"] = self.data_yaml   # set after prepare_dataset() resolves the path
        return {k: v for k, v in raw.items() if k not in exclude}


# ---------------------------------------------------------------------------
# Visualization
# ---------------------------------------------------------------------------

def _class_color(class_id: int) -> tuple[int, int, int]:
    """Deterministic, visually distinct RGB color derived from class index."""
    h = hashlib.md5(str(class_id).encode()).digest()
    r = (h[0] & 0xFF) | 0x40  # clamp to [64, 255] for readability
    g = (h[1] & 0xFF) | 0x40
    b = (h[2] & 0xFF) | 0x40
    return (r, g, b)


def draw_detections(
    image: Image.Image,
    boxes: list[tuple[float, float, float, float]],
    labels: list[int],
    scores: list[float],
    class_names: list[str],
    conf_threshold: float = 0.25,
) -> Image.Image:
    """Draw bounding boxes and labels onto *a copy* of the image.

    Args:
        image: Input PIL image (not mutated).
        boxes: List of (x1, y1, x2, y2) in absolute pixel coordinates.
        labels: Class index for each box.
        scores: Confidence score for each box.
        class_names: Full list of class name strings.
        conf_threshold: Boxes below this confidence are skipped.

    Returns:
        A new PIL Image with detections drawn.
    """
    result = image.copy()
    draw = ImageDraw.Draw(result)

    try:
        font = ImageFont.truetype("arial.ttf", size=18)
    except (IOError, OSError):
        font = ImageFont.load_default()

    for (x1, y1, x2, y2), label, score in zip(boxes, labels, scores):
        if score < conf_threshold:
            continue

        color = _class_color(label)
        draw.rectangle([x1, y1, x2, y2], outline=color, width=3)

        name = class_names[label] if label < len(class_names) else str(label)
        text = f"{name}: {score:.2f}"

        # Filled background rectangle for the text
        bbox = draw.textbbox((x1, y1), text, font=font)
        draw.rectangle(bbox, fill=color)
        draw.text((x1, y1), text, fill="white", font=font)

    return result


# ---------------------------------------------------------------------------
# WandB integration
# ---------------------------------------------------------------------------

def setup_wandb(config: TrainConfig) -> bool:
    """Initialise a WandB run from *config*.

    Returns True on success, False if WandB is unavailable (e.g. offline
    environment).  Callers should check the return value before calling
    ``wandb.finish()``.
    """
    try:
        import wandb  # noqa: PLC0415
    except ImportError:
        print("[wandb] wandb not installed — skipping WandB logging.")
        return False

    wandb.init(
        project=config.wandb_project,
        entity=config.wandb_entity or None,
        config=dataclasses.asdict(config),
        reinit=True,
    )
    return True
